<?php

namespace ContainerBbmiXuk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OIBAU7IService extends App_KernelProductionDebugContainer
{
    /**
     * Gets the private '.service_locator.OIBAU7I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OIBAU7I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'accessTokenHandler' => ['privates', 'App\\Security\\AccessTokenHandler', 'getAccessTokenHandlerService', true],
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
        ], [
            'accessTokenHandler' => 'App\\Security\\AccessTokenHandler',
            'authenticationUtils' => '?',
        ]);
    }
}
