<?php

namespace ContainerBbmiXuk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRedisService extends App_KernelProductionDebugContainer
{
    /**
     * Gets the private 'Redis' shared autowired service.
     *
     * @return \Redis
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Redis'] = $instance = new \Redis();

        $instance->connect($container->getEnv('key:host:url:REDIS_URL'), $container->getEnv('key:port:url:REDIS_URL'));
        $instance->auth($container->getEnv('REDIS_PASSWORD'));

        return $instance;
    }
}
