<?php

namespace ContainerLopblxM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RiD9_RdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RiD9.Rd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RiD9.Rd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'repo' => ['privates', 'App\\Repository\\JobPostRepository', 'getJobPostRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'logger' => '?',
            'repo' => 'App\\Repository\\JobPostRepository',
            'security' => '?',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
