<?php

namespace ContainerLopblxM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobPost2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Xm0eklc.App\Entity\JobPost' shared service.
     *
     * @return \App\Entity\JobPost
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Xm0eklc": it needs an instance of "App\\Entity\\JobPost" but this type has been excluded in "config/services.yaml".');
    }
}
