<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class JobPost extends \App\Entity\JobPost implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdate' => [parent::class, 'createdate', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'jobCategory' => [parent::class, 'jobCategory', null],
        "\0".parent::class."\0".'jobDescription' => [parent::class, 'jobDescription', null],
        "\0".parent::class."\0".'jobLocation' => [parent::class, 'jobLocation', null],
        "\0".parent::class."\0".'jobPosts' => [parent::class, 'jobPosts', null],
        "\0".parent::class."\0".'jobRequirement' => [parent::class, 'jobRequirement', null],
        "\0".parent::class."\0".'jobTitle' => [parent::class, 'jobTitle', null],
        "\0".parent::class."\0".'relatedApplicationForms' => [parent::class, 'relatedApplicationForms', null],
        "\0".parent::class."\0".'savedJobs' => [parent::class, 'savedJobs', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'createdate' => [parent::class, 'createdate', null],
        'id' => [parent::class, 'id', null],
        'jobCategory' => [parent::class, 'jobCategory', null],
        'jobDescription' => [parent::class, 'jobDescription', null],
        'jobLocation' => [parent::class, 'jobLocation', null],
        'jobPosts' => [parent::class, 'jobPosts', null],
        'jobRequirement' => [parent::class, 'jobRequirement', null],
        'jobTitle' => [parent::class, 'jobTitle', null],
        'relatedApplicationForms' => [parent::class, 'relatedApplicationForms', null],
        'savedJobs' => [parent::class, 'savedJobs', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
