<?php

namespace ContainerFfUeb7j;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_41gsk2PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.41gsk2P' shared service.
     *
     * @return \Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ForgetPasswordController::resetPasswordConfirm()": the $passwordEncoder argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface".');
    }
}
