<?php

namespace ContainerFfUeb7j;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PyE0C_IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pyE0C.I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pyE0C.I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'doctrine' => '?',
            'logger' => '?',
            'repo' => 'App\\Repository\\UserRepository',
            'slugger' => '?',
            'validator' => '?',
        ]);
    }
}
