<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBbmiXuk\App_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBbmiXuk/App_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/ContainerBbmiXuk.legacy');

    return;
}

if (!\class_exists(App_KernelProductionDebugContainer::class, false)) {
    \class_alias(\ContainerBbmiXuk\App_KernelProductionDebugContainer::class, App_KernelProductionDebugContainer::class, false);
}

return new \ContainerBbmiXuk\App_KernelProductionDebugContainer([
    'container.build_hash' => 'BbmiXuk',
    'container.build_id' => 'f9db8b1a',
    'container.build_time' => 1707659067,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBbmiXuk');
