<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_auth_login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login']], [], [], []],
    'app_auth_logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
    'api_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/api/register']], [], [], []],
    'api_confirm_email' => [[], ['_controller' => 'App\\Controller\\RegistrationController::confirmEmail'], [], [['text', '/api/confirm-email']], [], [], []],
    'App\Controller\LoginController::login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\LoginController::logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\RegistrationController::register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/api/register']], [], [], []],
    'App\Controller\RegistrationController::confirmEmail' => [[], ['_controller' => 'App\\Controller\\RegistrationController::confirmEmail'], [], [['text', '/api/confirm-email']], [], [], []],
];
