<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLopblxM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLopblxM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLopblxM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLopblxM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLopblxM\App_KernelDevDebugContainer([
    'container.build_hash' => 'LopblxM',
    'container.build_id' => '23eb1793',
    'container.build_time' => 1708522068,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLopblxM');
